# Generated by Django 4.1 on 2023-04-22 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closing_time',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
