# Generated by Django 4.1 on 2023-04-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_closing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(null=True),
        ),
    ]
